+ name: Generate
jobs:
+ # 生成统计图, see: https://github.com/lowlighter/metrics
+ github-metrics:
+   runs-on: ubuntu-latest
+   steps:
+     - name: metrics-Half-year-calendar
+       uses: lowlighter/metrics@latest
+       with:
+         base: ""
+         filename: assets/metrics.plugin.isocalendar.svg
+         token: ${{ github.token }}
+         plugin_isocalendar: yes
+ 
  github-Snake:
    runs-on: ubuntu-latest
  ....
